### ISSUE TITLE
Link to Styleguide 404s

### ISSUE THREAD

**Issue by KattMingMing** [reddit/baseplate.py#233]
The link to the styleguide from CONTRIBUTING.md under the linting section 404s. See https://github.com/reddit/baseplate/blob/master/CONTRIBUTING.md#linting

404 link - https://github.com/reddit/styleguide

Is there another URL where the Reddit styleguide can be found?

**Comment by spladug** [comment]
I've removed that document as it's quite out of date now. Sorry for the dead links. Our styleguide is basically PEP-8 with 100 column maximum.
