### ISSUE TITLE
Work queue in queue_consumer.py is unbounded

### ISSUE THREAD

**Issue by pacejackson** [reddit/baseplate.py#302]
The [work_queue](https://github.com/reddit/baseplate.py/blob/c7045c905a0ec2249a07e352f8dbceaf5ccd4303/baseplate/queue_consumer.py#L109) created in `queue_consumer.py` is currently un-bounded.  This means that if queue is **very** full, the kombu consumer will rapidly accept messages from RabbitMQ and fill the work_queue until the application runs out of memory.

To address this, we should set some value for `maxsize` when initializing the queue.

**Comment by spladug** [comment]
Fixed in 9e38a078f90c28f586d94e69fa2c86acad3b9108
