### ISSUE TITLE
Many baseplate connections hang due to an upstream bug in Gevent

### ISSUE THREAD

**Issue by fizx** [reddit/baseplate.py#389]
Upstream bug I filed: https://github.com/gevent/gevent/issues/1505

Gevent claims that [1]

    ``handle`` will be executed
            using :meth:`gevent.pool.Pool.spawn` only if the pool is not full.
            While it is full, no new connections are accepted

Unfortunately, the full check is stubbed out with "False" [2] such that the pool is never considered full.  I can't find anywhere in some subclass that this check might be overridden with a real check.  So this invariant appears broken upsteam.  

gevent.StreamServer looks like it's thread-per-connection.  The default pool behavior when full is blocking, not rejecting.  We appear to use a default bounded pool.

**The end result of this is that when max_connections is enabled in baseplate, we will accept a bunch of connections that we cannot service.  Those connections will simply hang.**

A simple reproduction [5] on a brand-new baseplate-cookiecutter project confirms this.

I know max_connections is deprecated, in part because we are suspicious of it.  Perhaps understanding the root cause of our trouble is useful, and then we can retain the value of a properly implemented max_connections.

Possible solutions:

1. Set the thread pool behavior to error-on-full instead of block-on-full.  This is low effort and will prevent the hanging behavior.
2. Wait for upstream to fix.
3. Look at the circuit-breaking [3, 4] PRs that fix this by not using the threadpool to be the concurrency limiter.

[1] https://github.com/gevent/gevent/blob/master/src/gevent/baseserver.py#L64
[2] https://github.com/gevent/gevent/blob/master/src/gevent/baseserver.py#L245
[3] https://github.com/reddit/baseplate.py/pull/383
[4] https://github.com/reddit/baseplate.py/pull/384
[5] Set max_concurrency to something low like 5, modify the test-client to log on connect, then leave the connection open after the request for 30s, then do 10 requests in parallel.  You'll get 10 successful connects and only 5 requests serviced.

**Comment by spladug** [comment]
This should be fixed by the removal of `max_concurrency` in 1.2.
