### ISSUE TITLE
No way to pass secrets to KombuProducer

### ISSUE THREAD

**Issue by aides** [reddit/baseplate.py#434]
According to docs (https://baseplate.readthedocs.io/en/stable/api/baseplate/clients/kombu.html?highlight=producer#example) I can configure KombuProducer in `configure_context` like:
```python
baseplate.configure_context(
   app_config,
   {
      ...
      "ampq": KombuProducer(),
      ...
   }
)
```
However right now the constructor doesn't accept secrets so it can't pass it to `connection_from_config` so it won't work with any custom credentials (and can confusingly work with default ones)

I suggest adding `secrets` parameter to `KombuProducer`'s `__init__` in the same manner as `SQLAlchemySession` has it. 

Otherwise the workaround is manually initialize KombuProducerContextFactory and add it to the context.

```python
connection = connection_from_config(app_config, prefix="amqp.", secrets=secrets)
exchange = exchange_from_config(app_config, prefix="amqp.")
baseplate.add_to_context("amqp", KombuProducerContextFactory(connection, exchange))
```

**Comment by pacejackson** [comment]
Ahh, good point.  

If you'd like this addressed sooner, please feel free to open a PR and we can review it.  I _think_ this should be a pretty straight forward change,  you could just add `secrets` as an optional argument to the [KombuProducer constructor](https://github.com/reddit/baseplate.py/blob/e557576f5b0c4e618069efe5b11c038b181c3a39/baseplate/clients/kombu.py#L168) (and add it as an attribute on the object) and then thread that into the [connection_from_config](https://github.com/reddit/baseplate.py/blob/e557576f5b0c4e618069efe5b11c038b181c3a39/baseplate/clients/kombu.py#L174) call it makes in `parse.

**Comment by aides** [comment]
Hey @pacejackson, 
Sure. I've opened this PR: https://github.com/reddit/baseplate.py/pull/451

**Comment by pacejackson** [comment]
https://github.com/reddit/baseplate.py/pull/451 has been merged
