### ISSUE TITLE
Unable to start live data sidecar without the secrets file

### ISSUE THREAD

**Issue by KTAtkinson** [reddit/baseplate.py#482]
The [live data sidecar documentation](https://baseplate.readthedocs.io/en/stable/api/baseplate/lib/live_data.html#watcher-daemon) allows for not using credentials to access Zookeeper, but the sidecar won't start unless the secrets file is populated. 

I would have expected the live data sidecar to start without a secrets file and gracefully fail if it access secrets and there are none. Alternately, ZK credentials could be required to run the sidecar.

**Command used to run sidecar**: exec python3 -m baseplate.sidecars.live_data_watcher $DEBUG "$CONFIG_PATH"

**Result**: This log indicates that the sidecar is not fetching live data because the secret file is not yet available.
```/var/local/secrets.json: file not yet available. sleeping.
/var/local/secrets.json: file not yet available. sleeping.
/var/local/secrets.json: file not yet available. sleeping.
/var/local/secrets.json: file not yet available. sleeping.
/var/local/secrets.json: file not yet available. sleeping.
/var/local/secrets.json: file not yet available. sleeping.
/var/local/secrets.json: file not yet available. sleeping.
/var/local/secrets.json: file not yet available. sleeping.
/var/local/secrets.json: file not yet available. sleeping.
/var/local/secrets.json: file not yet available. sleeping.
/var/local/secrets.json: file not yet available. sleeping.
```

**Comment by spladug** [comment]
Am I understanding correctly that you'd like to use the sidecar in a situation where no credentials are required to access a node in zookeeper?

**Comment by KTAtkinson** [comment]
I'm lost on what the context was here, sorry I'm closing as I think this is obsolete.
