### ISSUE TITLE
queue_consumer server does not start runtime_monitor

### ISSUE THREAD

**Issue by bsimpson63** [reddit/baseplate.py#484]
The thrift and wsgi servers both call `runtime_monitor.start()` within `make_server`, but the queue_consumer server does not.

**Comment by spladug** [comment]
This sounds like a good thing to have. Would you be interested in taking it on?

**Comment by bsimpson63** [comment]
Yeah I can do it

**Comment by spladug** [comment]
5c42019b8f4a8cb39ac334433b325646eeffaf6a
