### ISSUE TITLE
queue_consumer server does not handle server timeouts correctly

### ISSUE THREAD

**Issue by bsimpson63** [reddit/baseplate.py#485]
When the server timeout is exceeded gevent raises the `ServerTimeout` exception.

`ServerTimeout` inherits from `BaseException` instead of `Exception` to avoid getting caught by application code that does `except Exception: ...`.

The queue_consumer server runs a bunch of worker threads [wrapped in `try/except Exception` to catch exceptions and shut down all threads and kill the server](https://github.com/reddit/baseplate.py/blob/15811b3b4f9e55c3cd1d5f0e6591cb80d4f97852/baseplate/server/queue_consumer.py#L210). The server runs a http healthcheck endpoint so when it shuts down healthchecks will fail and hopefully the server will be restarted.

Because `ServerTimeout` isn't caught by the `except Exception` block the worker threads can die without killing the server and healthchecker, leaving the server running but in a broken state.

**Comment by spladug** [comment]
Just dropping the `Exception` part should fix it? Sounds good to me.

**Comment by spladug** [comment]
9ac69d659581e62d41c9859879132d3905330611
