### ISSUE TITLE
metrics: Make it possible to disable logging on NullReporter

### ISSUE THREAD

**Issue by bsimpson63** [reddit/baseplate.py#500]
The current NullReporter logs but doesn't send metrics https://github.com/reddit/baseplate.py/blob/41ab42ffcfb72f9b26b3a916a69eccbf107c7ae8/baseplate/lib/metrics.py#L102. This can be kind of noisy for local development so there should be an option to get it to not log.

**Comment by spladug** [comment]
Fixed in aec186fbae2db7822d59c9729b5598f40a3f43eb, thanks @bsimpson63 !
