### ISSUE TITLE
Can baseplate play with bottlepy?

### ISSUE THREAD

**Issue by liuzhijun** [reddit/baseplate.py#541]

**Comment by liuzhijun** [comment]
https://baseplate.readthedocs.io/en/stable/tutorial/chapter1/index.html
Pyramid is also to complex.
Thank you very much!

**Comment by spladug** [comment]
Hi! We're pretty unlikely to add bottle support ourselves, but if you wanted to do it you'd want to create a new framework integration. Here's how Pyramid is integrated: https://github.com/reddit/baseplate.py/blob/develop/baseplate/frameworks/pyramid/__init__.py . This could happily live in a separate library as well.

Thanks for your interest!
