### ISSUE TITLE
Improve the script command

### ISSUE THREAD

**Issue by spladug** [reddit/baseplate.py#58]
* [Allow the script to parse arguments itself](https://github.com/reddit/baseplate/pull/56#issuecomment-258165931)
* Make it possible to run scripts directly by filename rather than doing global module lookup.
* Ponder more on how to set up a nice environment in the script sanely.

**Comment by spladug** [comment]
How can we make health checks a thing for daemons?

**Comment by bradengroom** [comment]
> Allow the script to parse arguments itself

+1 on this part. We've had to break out of `baseplate-script` a couple of times now just so we can parse arguments.

**Comment by bradengroom** [comment]
What would passing arguments to the underlying script look like? I've seen this syntax in a couple of places:
`vagrant ssh -- -R 9090:localhost:9090`

Maybe a similar syntax would make sense?
`baseplate-script example.ini some.module:run -- --my-option=foo`

**Comment by AngryEgret** [comment]
`parser.add_argument('args', nargs=argparse.REMAINDER)` might be enough.

**Comment by spladug** [comment]
This was fixed by @bradengroom in d79ddda5a566019055dd537e80822c932c911d9f

**Comment by spladug** [comment]
> Make it possible to run scripts directly by filename rather than doing global module lookup.

and this should be possible with 78d27b8067aebcf80a3d00d694fa3ee8851e68d4
