### ISSUE TITLE
Fix str/bytes confusion in crypto signer API

### ISSUE THREAD

**Issue by spladug** [reddit/baseplate.py#97]
From @pacejackson:

> `crypto.make_signature` returns a "bytes" object but `crypto.verify_signature` says that `signature` should be a str.  In practice, a string or a bytes object for `signature` works because the base64 decode methods started accepting both bytes and strings in python 3.3

**Comment by spladug** [comment]
I think this is fixed in https://github.com/reddit/baseplate.py/pull/293

Do you agree, @pacejackson ?

**Comment by pacejackson** [comment]
Yep!
